# 打印Debug日志
debug: true
logging:
  level: { tech.ordinaryroad: debug }
spring:
  # 数据库配置
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/ordinaryroad_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: root
          password: root
  # 出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
# swagger配置
swagger:
  title: 系统模块接口文档
  license: Powered By OrdinaryRoad
  licenseUrl: https://ordinaryroad.top