# Tomcat
server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    # 应用名称
    name: ordinaryroad-upms
  # 数据库配置
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/ordinaryroad_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: root
          password: root