version: "2"
services:
  ordinaryroad-ui:
    image: ordinaryroad-ui
    container_name: ordinaryroad-ui
    build:
      context: ./ordinaryroad-ui
    volumes:
      - $PWD/ordinaryroad-ui/app:/ordinaryroad/ordinaryroad-ui/app
    hostname: ordinaryroad-ui
    restart: always

  ordinaryroad-nginx:
    image: ordinaryroad-nginx
    container_name: ordinaryroad-nginx
    build:
      context: ./ordinaryroad-nginx
    volumes:
      - $PWD/ordinaryroad-nginx/ssl:/etc/nginx/ssl
    ports:
      # 前端
      - "8021:8021"
      # 网关 https
      - "8090:8090"
      # 认证服务器 https
      - "8302:8302"
      # nacos https
      - "9848:9848"
      # minio console https
      - "9001:9001"
    depends_on:
      - ordinaryroad-gateway
      - ordinaryroad-ui
      - ordinaryroad-minio
    restart: always

  ordinaryroad-redis:
    image: ordinaryroad-redis
    container_name: ordinaryroad-redis
    build:
      context: ./ordinaryroad-redis
    volumes:
      - $PWD/ordinaryroad-redis/data:/data
    hostname: ordinaryroad-redis
    restart: always

  ordinaryroad-mysql:
    image: ordinaryroad-mysql
    container_name: ordinaryroad-mysql
    build:
      context: ./ordinaryroad-mysql
    volumes:
      - $PWD/ordinaryroad-mysql/etc/my.cnf:/etc/my.cnf
      - $PWD/ordinaryroad-mysql/data:/var/lib/mysql
    ports:
      - "3307:3307"
    hostname: ordinaryroad-mysql
    restart: always

  ordinaryroad-nacos:
    image: ordinaryroad-nacos
    container_name: ordinaryroad-nacos
    build:
      context: ./ordinaryroad-nacos
    volumes:
      - $PWD/ordinaryroad-nacos/standalone-logs:/home/nacos/logs
    depends_on:
      - ordinaryroad-mysql
    hostname: ordinaryroad-nacos
    restart: always

  ordinaryroad-minio:
    image: ordinaryroad-minio
    container_name: ordinaryroad-minio
    build:
      context: ./ordinaryroad-minio
    volumes:
      - $PWD/ordinaryroad-minio/data:/data
      - $PWD/ordinaryroad-minio/config:/root/.minio
    hostname: ordinaryroad-minio
    restart: always
    command: server /data --console-address ":9999"

  ordinaryroad-gateway:
    image: ordinaryroad-gateway
    container_name: ordinaryroad-gateway
    build:
      context: ./ordinaryroad-gateway
    depends_on:
      - ordinaryroad-auth-server
      - ordinaryroad-upms
      - ordinaryroad-push
    hostname: ordinaryroad-gateway
    restart: always

  ordinaryroad-auth-server:
    image: ordinaryroad-auth-server
    container_name: ordinaryroad-auth-server
    build:
      context: ./ordinaryroad-auth-server
    depends_on:
      - ordinaryroad-mysql
      - ordinaryroad-redis
      - ordinaryroad-nacos
      - ordinaryroad-upms
    hostname: ordinaryroad-auth-server
    restart: always

  ordinaryroad-upms:
    image: ordinaryroad-upms
    container_name: ordinaryroad-upms
    build:
      context: ./ordinaryroad-upms
    depends_on:
      - ordinaryroad-mysql
      - ordinaryroad-redis
      - ordinaryroad-nacos
      - ordinaryroad-push
    hostname: ordinaryroad-upms
    restart: always

  ordinaryroad-push:
    image: ordinaryroad-push
    container_name: ordinaryroad-push
    build:
      context: ./ordinaryroad-push
    depends_on:
      - ordinaryroad-mysql
      - ordinaryroad-redis
      - ordinaryroad-nacos
    hostname: ordinaryroad-push
    restart: always