# Tomcat
server:
  port: 9090

# Spring
spring:
  application:
    # 应用名称
    name: ordinaryroad-gateway
  profiles:
    # 环境配置
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: ordinaryroad-authenticate
          uri: http://localhost:9301
          predicates:
            - Path=/authenticate/**
          filters:
            # 验证码处理
            # - CacheRequestFilter
            # - ValidateCodeFilter
            - StripPrefix=1
        # 授权中心
        - id: ordinaryroad-authorization-server
          uri: http://localhost:9302
          predicates:
            - Path=/authorization/**
          filters:
            # 验证码处理
            # - CacheRequestFilter
            # - ValidateCodeFilter
            - StripPrefix=1 #前缀， 在当前路径匹配中表示去掉第一个前缀 /authorization-server
        # 系统模块
        - id: ordinaryroad-system
          #          uri: lb://ordinaryroad-system
          uri: http://localhost:9401
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
    consul:
      discovery:
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        prefer-ip-address: true
        hostname: 127.0.0.1
        port: 8500
        heartbeat:
          enabled: true
        register: false
        service-name: ${spring.application.name}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9302/oauth2/default/v1/keys
          # URI 可以是 OpenID Connect 发现端点或 RFC 8414 定义的 OAuth 2.0 授权服务器元数据端点。
          issuer-uri: http://auth-server:9302
      client:
        provider:
          spring:
            issuer-uri: http://auth-server:9302

  main:
    allow-bean-definition-overriding: true