spring:
  redis:
    host: localhost
    port: 6379
    password:
  devtools:
    livereload:
      port: 35730
# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /**
      - /authenticate
      - /authenticate/logout
      - /authenticate/login
      - /authenticate/register
      - /*/v2/api-docs
      - /csrf
#    whites:
#      - /auth/logout
#      - /auth/login
#      - /auth/register
#      - /*/v2/api-docs
#      - /csrf