sa-token:
  oauth2:
    auth-server-host: lb://ordinaryroad-auth-server/oauth2
# Tomcat
server:
  port: 9090
spring:
  profiles:
    active: dev
  application:
    # 应用名称
    name: ordinaryroad-gateway
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  cloud:
    gateway:
      routes:
        - id: ordinaryroad-auth-server
          uri: lb://ordinaryroad-auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: ordinaryroad-upms
          uri: lb://ordinaryroad-upms
          predicates:
            - Path=/upms/**
          filters:
            - StripPrefix=1
