# Tomcat
server:
  port: 9302
# Spring
spring:
  datasource:
    username: root
  application:
    # 应用名称
    name: ordinaryroad-authorization-server
  profiles:
    # 环境配置
    active: dev
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        prefer-ip-address: true
        hostname: 127.0.0.1
        port: 8500
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}